### PR TITLE
Support User ID tracking via setUserId

### PR DESCRIPTION
**Pull request by kevinoid**
This PR adds support for the new `setUserId` method added in piwik/piwik#3490 and documented at https://piwik.org/docs/user-id/

I wasn't sure what the correct ordering is for `PiwikActionMethods`, so I put this method at the end.  Let me know if there is a particular order of these methods and I'll resubmit with a corrected ordering.

Thanks,
Kevin

### CODE REVIEW

**Comment by mike-spainhower** [comment]
Excellent, thanks for the PR.  IIRC, this should be benign when used with older versions of piwik, right?

**Comment by kevinoid** [comment]
My pleasure.  Thanks for the quick merge!

It's not completely benign in the sense that if the user calls `Piwik.setUserId` and is using a version of `piwik.js` earlier than 2.7.0 I am pretty sure they will get an error due to calling a missing method.  However, that seems like a pretty reasonable behavior (although the error message could be better).  If you are concerned about it, we could brainstorm better behavior for this case.

**Comment by mike-spainhower** [comment]
This ng service strictly uses the async command queue (https://github.com/mike-spainhower/angular-piwik/blob/master/lib/angular-piwik.coffee#L80) rather than directly calling methods.  I am not familiar enough with Piwik's internals to know how gracefully it handles unknown commands being placed on the queue.  This is probably fine.

**Comment by kevinoid** [comment]
Right.  Before `piwik.js` loads they get deferred (and probably cause an unhandled error, although I haven't checked).  After load Piwik replaces `_paq.push` with a proxy to call the methods immediately, so the error is raised at the call point. (which is great for debugging).

It seems pretty reasonable to me too, but if you run into a reason to change it later, let me know and I'll help.

Thanks again!

**Comment by mike-spainhower** [comment]
> After load Piwik replaces _paq.push with a proxy to call the methods immediately

oh wow.  does it at least do so asynchronously?  Some async error that shows up in the console window but doesn't affect other things on the event loop is fine, but crashing whatever called our ng service would be a bummer!

**Comment by kevinoid** [comment]
I'll confirm to make sure.  (I could be misremembering.)  If it is the case, we can wrap the push call in a try-catch and pass any exceptions to `$exceptionHandler`, or whatever you would prefer here.

**Comment by kevinoid** [comment]
Yep, definitely synchronous after `piwik.js` had been loaded.  The call goes through [TrackerProxy](https://github.com/piwik/piwik/blob/2.11.2/js/piwik.js#L5208) which replaces `_paq` to [apply](https://github.com/piwik/piwik/blob/2.11.2/js/piwik.js#L579) to [setUserId](https://github.com/piwik/piwik/blob/2.11.2/js/piwik.js#L4247) (or any other method).

Personally, I'd let the exception propagate so the caller can catch it if they choose, but if you'd prefer to have angular-piwik catch and log it without the caller's awareness, I can submit a PR with that behavior.

**Comment by mike-spainhower** [comment]
> I'd let the exception propagate so the caller can catch it if they choose

Reasonable.

**Pull request merged**
