### PR TITLE
Fix: Missing Methods for Latest version of Piwik

### LINKED ISSUE #12: Missing Methods for Latest version of Piwik
I have noticed that the method arrays for the Piwik service are missing some entries.

I am running Piwik 1.12.1 and the missing action methods are:

    setCustomRequestProcessing
    appendToTrackingUrl
    addPlugin
    storeCustomVariablesInCookie
    setRequestContentType
    setAPIUrl
    disableCookies
    deleteCookies
    enableJSErrorTracking
    disablePerformanceTracking
    setGenerationTimeMs
    trackAllContentImpressions
    trackVisibleContentImpressions
    trackContentImpression
    trackContentImpressionsWithinNode
    trackContentInteraction
    trackContentInteractionNode
    trackSiteSearch

the missing get methods are:

    getTrackerUrl
    getSiteId
    getUserId
    getRequest

I am currently working around this in my own module by decorating the `PiwikActionMethods` and `PiwikGetMethods` with the missing functions.

    angular.module('my-piwik', ['piwik'])
        .config(['$provide', function ($provide) {
            var missingPiwikActionMethods = [...];

            $provide.decorator('PiwikActionMethods', ['$delegate', function ($delegate) {
                return $delegate.concat(missingPiwikActionMethods);
            }]);
        }]);

### PR DESCRIPTION
**Pull request by mike-spainhower**
* Add methods that get angular-piwik up-to-date with 1.12.1

Closes #12

### CODE REVIEW

**Comment by mike-spainhower** [comment]
@traviscosgrave does this appear to fix #12?  If so I will merge.

**Comment by traviscosgrave** [comment]
I believe it does. My work around was simply adding those methods to the arrays. I found the missing methods by comparing the existing arrays to calling `Piwik.getTracker()` in the browser console.

Thanks for the quick work.

**Comment by traviscosgrave** [comment]
Will this make it to the bower project soon?

**Comment by mike-spainhower** [comment]
> Will this make it to the bower project soon?

Need to automate that :eyes: .  Regret making a separate repo as was en vogue back when I chose to IIRC.

This is done.

**Pull request merged**
