### PR TITLE
Duplicate calls

### PR DESCRIPTION
**Pull request by petergillardmoss**
This is my implementation of https://github.com/mike-spainhower/angular-piwik/pull/3

The original implementation ignored subsequent requests.  This implementation updates the existing calls in the _paq queue if they exist.

Firstly, apologies for my coffeescript, I'm not very familiar with the language so I'm happy to accept any suggestions for improvements.

Also, there may be a better way of doing this, perhaps having a hash that gets pushed to the queue at a later point in the lifecycle.  However I don't know the piwik library well enough to take a different approach.  If you have a better one let me know and I'll refactor.

Thanks
Peter

### CODE REVIEW

**Comment by vikbez** [comment]
:+1:

**Comment by mike-spainhower** [comment]
This looks reasonable.  Sorry for the delay!

**Comment by mike-spainhower** [comment]
I'll get this published in a bit, thanks again

**Comment by mike-spainhower** [comment]
Published to bower - https://github.com/mike-spainhower/bower-angular-piwik/releases/tag/1.3.1

**Comment by vikbez** [comment]
thanks ! :kiss:

**Pull request merged**
