### PR TITLE
Update angular-piwik.coffee

### PR DESCRIPTION
**Pull request by fbakiri**
Add trackEvent method in PiwikActionMethods (http://piwik.org/docs/event-tracking/)

### CODE REVIEW

**Comment by mike-spainhower** [comment]
Thanks for the PR.  This appears to be a dupe of https://github.com/mike-spainhower/angular-piwik/pull/2

If you want to add the test, compile the js, and rebase on `master`, I am happy to merge this when it's passing on Travis a well.

**Comment by gordanvij** [comment]
Will this be merged soon? trackEvent is a much used method, which is required for me.

**Comment by gordanvij** [comment]
Thanks for the quick turn around. Much appreciate it.

**Comment by mike-spainhower** [comment]
not a problem

**Pull request closed without merging**
