### PR TITLE
Prevent duplicate calls to setTrackerUrl and setSiteId during ngpPiwik directive compilation.

### PR DESCRIPTION
**Pull request by gowravshekar**
Please review and merge the fork changes to master repository.

### CODE REVIEW

**Comment by nidico** [comment]
@mike-spainhower: any updates here?

**Comment by mike-spainhower** [comment]
@nidico Thanks for pinging on this.  I sadly lost my patch, but can probably whip another one together pretty quickly in the next few days.

**Comment by nidico** [comment]
Great!

**Comment by mike-spainhower** [comment]
Haven't yet gotten to this, but still on the queue

**Comment by traviscosgrave** [comment]
I've taken a look at this, and based on the PR the updated `post` function would be:

    post: (scope, elem, attrs) ->
      cache_action_vals = {}
      for own k,v of attrs when /^ngp/.test(k)
        do (k,v) ->
          method = k[3].toLowerCase() + k[4..]
          return if not (method in PiwikActionMethods)
          cache_action_vals[method] = v
          $window['_paq'].push build_p_call(method, v)
          attrs.$observe k, (val) ->
            if cache_action_vals[method] isnt val
              cache_action_vals[method] = val
              $window['_paq'].push build_p_call(method, val)
      $window['_paq'].push ['trackPageView']

And this directive test will need to be updated:

    it 'should create call queue', ->
      expect(win['_paq']).toBeDefined()
      console.log(win['_paq'])
      expect(win['_paq'].length).toEqual(4)

I suppose a test verifying that a changing value causes a new push to the piwik queue and one that checks that no push is made if the value doesn't change might be required.

I did notice though, that when trying to test scope-bound values (`{{tracker_url}}`) I got an error. It looks like this is caused because the attribute value isn't being `$parse`ed, even though the `$observe` function will interpolate the value. This makes me wonder, is the `$observe` even useful in this case?There is no support for dynamic values in the directive, nor does that kind of functionality seem to be tested.

If the values really are 'bind-once', then the post function could look like this?

    post: (scope, elem, attrs) ->
      for own k,v of attrs when /^ngp/.test(k)
        do (k,v) ->
          method = k[3].toLowerCase() + k[4..]
          return if not (method in PiwikActionMethods)
          $window['_paq'].push build_p_call(method, v)
      $window['_paq'].push ['trackPageView']

**Comment by mike-spainhower** [comment]
@traviscosgrave would you have any interest in opening up a new PR with the code you provided?  I would be happy to review and merge if it looks good.

**Comment by mike-spainhower** [comment]
Closed by https://github.com/mike-spainhower/angular-piwik/pull/17

**Pull request closed without merging**
